# Config file for hyperparameter definition
train: true
learning_rate: 0.0003
epochs: 1000
logs: normal_kidneys_non_contrast_exp5
device: cuda
val_interval: 5
data_dir: D:\Users\kkouko0\DATASETS\GLONCO_NON_CONTRAST
# data_dir: /usr/local/micapollo01/MIC/DATA/STUDENTS/kkouko0/DATA/GLONCO_NON_CONTRAST/GLONCO_NON_CONTRAST_Train_eval/
dataset: CacheDataset
cross_val_split: 0.8
use_seed: false
seed: 0

# Dataloader
dataloader:
  batch_size: 4
  num_workers: 2
  shuffle: false

# Optimizer
optimizer: 
  name: 'Adam'
  learning_rate: 0.0003
  betas: [0.9, 0.999]
  epsilon: 0.00000008
  weight_decay: 0

# Learning rate scheduler
# sceduler:
#   name: 'CosineAnnealingWarmRestarts'
#   T_0: 30
#   eta_min: 1e-4 

# Loss function
loss:
  name: 'DiceLoss'
  include_background: true
  softmax: true

# Metric 
metric:
  name: 'DiceMetric'
  include_background: False
  reduction: 'mean'

# # Model selection
# model:
#   name: 'UNETR'
#   in_channels: 4
#   out_channels: 3
#   img_size: [96,96,96]
#   feature_size: 16
#   hidden_size: 768
#   mlp_dim: 3072
#   num_heads: 12
#   pos_embed: 'perceptron'
#   norm_name: 'instance'
#   conv_block: true
#   res_block: true
#   dropout_rate: 0.1
model:
  name: 'UNet'
  spatial_dims: 3
  in_channels: 1
  out_channels: 3
  kernel_size: 3
  up_kernel_size: 3
  channels: [32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2]
  num_res_units: 2
  dropout: 0.3
  norm: 'instance'

# Train transformations
train_transforms:
  LoadImaged_im:
      keys: ['image']
      ensure_channel_first: True
  LoadImaged_seg:
      keys: ['right_seg', 'left_seg']
      ensure_channel_first: True
  Spacingd_im:
      keys: ['image']
      pixdim: [1.5, 1.5, 1.5]
  Spacingd_seg:
      keys: ['right_seg', 'left_seg']
      pixdim: [1.5, 1.5, 1.5]
      mode: 'nearest'
  Flipd:
      keys: ['right_seg', 'left_seg']
      spatial_axis: [2]
  Transposed_im:
      keys: ['image']
      indices: [0, 2, 1, 3]
  Transposed_seg:
      keys: ['right_seg', 'left_seg']
      indices: [0, 2, 1, 3]
  WindowindNonContrastCTd:
      keys: ['image']
  ConvertToMultiChannelMaskd:
      keys: ['right_seg', 'left_seg']
  SpatialPadd:
      keys: ['image', segmentation]
      spatial_size: [96, 96, 96]
  RandSpatialCropSamplesd:
      keys: ['image', 'segmentation']
      roi_size: [96, 96, 96]
      num_samples: 1
      random_size: false
  RandFlipd_x:
      keys: ['image', 'segmentation']
      prob: 0
      spatial_axis: 0
  RandFlipd_y:
      keys: ['image', 'segmentation']
      prob: 0
      spatial_axis: 1
  RandFlipd_z:
      keys: ['image', 'segmentation']
      prob: 0
      spatial_axis: 2
  RandShiftIntensityd:
      keys: ['image', 'segmentation']
      prob: 0
      offsets: 0.1
  RandGaussianNoised:
      keys: ['image', 'segmentation']
      prob: 0
      mean: 0
      std: 0.05
  ThresholdIntensityd_clip_upper:
      keys: ['image', 'segmentation']
      threshold: 1.0
      above: False
      cval: 1.0
  ThresholdIntensityd_clip_lower:
      keys: ['image', 'segmentation'] 
      threshold: 0.0
      above: True
      cval: 0.0
  ToTensord:
      keys: ['image', 'segmentation']

# Validation transformations
eval_transforms:
  LoadImaged_im:
      keys: ['image']
      ensure_channel_first: True
  LoadImaged_seg:
      keys: ['right_seg', 'left_seg']
      ensure_channel_first: True
  Spacingd_im:
      keys: ['image']
      pixdim: [1.5, 1.5, 1.5]
  Spacingd_seg:
      keys: ['right_seg', 'left_seg']
      pixdim: [1.5, 1.5, 1.5]
      mode: 'nearest'
  Flipd:
      keys: ['right_seg', 'left_seg']
      spatial_axis: [2]
  Transposed_im:
      keys: ['image']
      indices: [0, 2, 1, 3]
  Transposed_seg:
      keys: ['right_seg', 'left_seg']
      indices: [0, 2, 1, 3]
  WindowindNonContrastCTd:
      keys: ['image']
  ConvertToMultiChannelMaskd:
      keys: ['right_seg', 'left_seg']
  SpatialPadd:
      keys: ['image', segmentation]
      spatial_size: [96, 96, 96]
  ToTensord:
      keys: ['image', 'segmentation']

# Post prediction transformations
post_pred_transforms:
  EnsureType:
  AsDiscrete:
      argmax: True
      to_onehot: 3